//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_Cilent.WCF_Synthese_Remote {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentaireDTO", Namespace="http://schemas.datacontract.org/2004/07/BO_Synthese.DTO")]
    [System.SerializableAttribute()]
    public partial class CommentaireDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TexteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int observationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsager {
            get {
                return this.IDUsagerField;
            }
            set {
                if ((this.IDUsagerField.Equals(value) != true)) {
                    this.IDUsagerField = value;
                    this.RaisePropertyChanged("IDUsager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texte {
            get {
                return this.TexteField;
            }
            set {
                if ((object.ReferenceEquals(this.TexteField, value) != true)) {
                    this.TexteField = value;
                    this.RaisePropertyChanged("Texte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int observationId {
            get {
                return this.observationIdField;
            }
            set {
                if ((this.observationIdField.Equals(value) != true)) {
                    this.observationIdField = value;
                    this.RaisePropertyChanged("observationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntiteWCFBase", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TEST_Cilent.WCF_Synthese_Remote.OiseauWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TEST_Cilent.WCF_Synthese_Remote.PhotoWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TEST_Cilent.WCF_Synthese_Remote.AlerteWCF))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TEST_Cilent.WCF_Synthese_Remote.UsagerWCF))]
    public partial class EntiteWCFBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageErreurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageErreur {
            get {
                return this.MessageErreurField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageErreurField, value) != true)) {
                    this.MessageErreurField = value;
                    this.RaisePropertyChanged("MessageErreur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OiseauWCF", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class OiseauWCF : TEST_Cilent.WCF_Synthese_Remote.EntiteWCFBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF[] CrisOiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspeceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.PhotoWCF[] PhotosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF[] CrisOiseau {
            get {
                return this.CrisOiseauField;
            }
            set {
                if ((object.ReferenceEquals(this.CrisOiseauField, value) != true)) {
                    this.CrisOiseauField = value;
                    this.RaisePropertyChanged("CrisOiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Espece {
            get {
                return this.EspeceField;
            }
            set {
                if ((object.ReferenceEquals(this.EspeceField, value) != true)) {
                    this.EspeceField = value;
                    this.RaisePropertyChanged("Espece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.PhotoWCF[] Photos {
            get {
                return this.PhotosField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotosField, value) != true)) {
                    this.PhotosField = value;
                    this.RaisePropertyChanged("Photos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriOiseauWCF", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class CriOiseauWCF : TEST_Cilent.WCF_Synthese_Remote.EntiteWCFBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOiseau {
            get {
                return this.IDOiseauField;
            }
            set {
                if ((this.IDOiseauField.Equals(value) != true)) {
                    this.IDOiseauField = value;
                    this.RaisePropertyChanged("IDOiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Son {
            get {
                return this.SonField;
            }
            set {
                if ((object.ReferenceEquals(this.SonField, value) != true)) {
                    this.SonField = value;
                    this.RaisePropertyChanged("Son");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoWCF", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class PhotoWCF : TEST_Cilent.WCF_Synthese_Remote.EntiteWCFBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOiseau {
            get {
                return this.IDOiseauField;
            }
            set {
                if ((this.IDOiseauField.Equals(value) != true)) {
                    this.IDOiseauField = value;
                    this.RaisePropertyChanged("IDOiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlerteWCF", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class AlerteWCF : TEST_Cilent.WCF_Synthese_Remote.EntiteWCFBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.OiseauWCF OiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.UsagerWCF UsagerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOiseau {
            get {
                return this.IDOiseauField;
            }
            set {
                if ((this.IDOiseauField.Equals(value) != true)) {
                    this.IDOiseauField = value;
                    this.RaisePropertyChanged("IDOiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsager {
            get {
                return this.IDUsagerField;
            }
            set {
                if ((this.IDUsagerField.Equals(value) != true)) {
                    this.IDUsagerField = value;
                    this.RaisePropertyChanged("IDUsager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCF Oiseau {
            get {
                return this.OiseauField;
            }
            set {
                if ((object.ReferenceEquals(this.OiseauField, value) != true)) {
                    this.OiseauField = value;
                    this.RaisePropertyChanged("Oiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.UsagerWCF Usager {
            get {
                return this.UsagerField;
            }
            set {
                if ((object.ReferenceEquals(this.UsagerField, value) != true)) {
                    this.UsagerField = value;
                    this.RaisePropertyChanged("Usager");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsagerWCF", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class UsagerWCF : TEST_Cilent.WCF_Synthese_Remote.EntiteWCFBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourrielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstAdministrateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotDePasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsagerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Courriel {
            get {
                return this.CourrielField;
            }
            set {
                if ((object.ReferenceEquals(this.CourrielField, value) != true)) {
                    this.CourrielField = value;
                    this.RaisePropertyChanged("Courriel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstAdministrateur {
            get {
                return this.EstAdministrateurField;
            }
            set {
                if ((this.EstAdministrateurField.Equals(value) != true)) {
                    this.EstAdministrateurField = value;
                    this.RaisePropertyChanged("EstAdministrateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotDePasse {
            get {
                return this.MotDePasseField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseField, value) != true)) {
                    this.MotDePasseField = value;
                    this.RaisePropertyChanged("MotDePasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsager {
            get {
                return this.NomUsagerField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsagerField, value) != true)) {
                    this.NomUsagerField = value;
                    this.RaisePropertyChanged("NomUsager");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OiseauWCFList", Namespace="http://schemas.datacontract.org/2004/07/WCF_Synthese.EntitesWCF")]
    [System.SerializableAttribute()]
    public partial class OiseauWCFList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.OiseauWCF[] OiseauxWCFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QteTotaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCF[] OiseauxWCF {
            get {
                return this.OiseauxWCFField;
            }
            set {
                if ((object.ReferenceEquals(this.OiseauxWCFField, value) != true)) {
                    this.OiseauxWCFField = value;
                    this.RaisePropertyChanged("OiseauxWCF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QteTotale {
            get {
                return this.QteTotaleField;
            }
            set {
                if ((this.QteTotaleField.Equals(value) != true)) {
                    this.QteTotaleField = value;
                    this.RaisePropertyChanged("QteTotale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObservationDTO", Namespace="http://schemas.datacontract.org/2004/07/BO_Synthese")]
    [System.SerializableAttribute()]
    public partial class ObservationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateObservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDOiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ListePhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.OiseauDTO OiseauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TEST_Cilent.WCF_Synthese_Remote.UsagerDTO UsagerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateObservation {
            get {
                return this.DateObservationField;
            }
            set {
                if ((object.ReferenceEquals(this.DateObservationField, value) != true)) {
                    this.DateObservationField = value;
                    this.RaisePropertyChanged("DateObservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDOiseau {
            get {
                return this.IDOiseauField;
            }
            set {
                if ((this.IDOiseauField.Equals(value) != true)) {
                    this.IDOiseauField = value;
                    this.RaisePropertyChanged("IDOiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsager {
            get {
                return this.IDUsagerField;
            }
            set {
                if ((this.IDUsagerField.Equals(value) != true)) {
                    this.IDUsagerField = value;
                    this.RaisePropertyChanged("IDUsager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListePhoto {
            get {
                return this.ListePhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListePhotoField, value) != true)) {
                    this.ListePhotoField = value;
                    this.RaisePropertyChanged("ListePhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.OiseauDTO Oiseau {
            get {
                return this.OiseauField;
            }
            set {
                if ((object.ReferenceEquals(this.OiseauField, value) != true)) {
                    this.OiseauField = value;
                    this.RaisePropertyChanged("Oiseau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre {
            get {
                return this.TitreField;
            }
            set {
                if ((object.ReferenceEquals(this.TitreField, value) != true)) {
                    this.TitreField = value;
                    this.RaisePropertyChanged("Titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TEST_Cilent.WCF_Synthese_Remote.UsagerDTO Usager {
            get {
                return this.UsagerField;
            }
            set {
                if ((object.ReferenceEquals(this.UsagerField, value) != true)) {
                    this.UsagerField = value;
                    this.RaisePropertyChanged("Usager");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OiseauDTO", Namespace="http://schemas.datacontract.org/2004/07/BO_Synthese.DTO")]
    [System.SerializableAttribute()]
    public partial class OiseauDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspeceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Espece {
            get {
                return this.EspeceField;
            }
            set {
                if ((object.ReferenceEquals(this.EspeceField, value) != true)) {
                    this.EspeceField = value;
                    this.RaisePropertyChanged("Espece");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsagerDTO", Namespace="http://schemas.datacontract.org/2004/07/BO_Synthese.DTO")]
    [System.SerializableAttribute()]
    public partial class UsagerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsagerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsager {
            get {
                return this.NomUsagerField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsagerField, value) != true)) {
                    this.NomUsagerField = value;
                    this.RaisePropertyChanged("NomUsager");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListePhotoObservationDTO", Namespace="http://schemas.datacontract.org/2004/07/BO_Synthese.DTO")]
    [System.SerializableAttribute()]
    public partial class ListePhotoObservationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDObservationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] photoListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDObservation {
            get {
                return this.IDObservationField;
            }
            set {
                if ((this.IDObservationField.Equals(value) != true)) {
                    this.IDObservationField = value;
                    this.RaisePropertyChanged("IDObservation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] photoList {
            get {
                return this.photoListField;
            }
            set {
                if ((object.ReferenceEquals(this.photoListField, value) != true)) {
                    this.photoListField = value;
                    this.RaisePropertyChanged("photoList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Synthese_Remote.IServiceWCF_Synthese")]
    public interface IServiceWCF_Synthese {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeleteCommentaire", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeleteCommentaireResponse")]
        void DeleteCommentaire(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/AddCommentaire", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/AddCommentaireResponse")]
        TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO AddCommentaire(TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO commentaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetCommentaire", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetCommentaireResponse")]
        TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO[] GetCommentaire(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetUsager", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetUsagerResponse")]
        TEST_Cilent.WCF_Synthese_Remote.UsagerWCF GetUsager(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/InsertUsager", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/InsertUsagerResponse")]
        TEST_Cilent.WCF_Synthese_Remote.UsagerWCF InsertUsager(TEST_Cilent.WCF_Synthese_Remote.UsagerWCF pUsager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/UpdateUsager", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/UpdateUsagerResponse")]
        TEST_Cilent.WCF_Synthese_Remote.UsagerWCF UpdateUsager(TEST_Cilent.WCF_Synthese_Remote.UsagerWCF pUsager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeleteUsager", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeleteUsagerResponse")]
        string DeleteUsager(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.OiseauWCF GetOiseau(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetAllOiseaux", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetAllOiseauxResponse")]
        TEST_Cilent.WCF_Synthese_Remote.OiseauWCFList GetAllOiseaux(string pStart, string pQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/InsertOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/InsertOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.OiseauWCF InsertOiseau(TEST_Cilent.WCF_Synthese_Remote.OiseauWCF pOiseau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/UpdateOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/UpdateOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.OiseauWCF UpdateOiseau(TEST_Cilent.WCF_Synthese_Remote.OiseauWCF pOiseau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeleteOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeleteOiseauResponse")]
        string DeleteOiseau(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetCriOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetCriOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF GetCriOiseau(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/InsertCriOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/InsertCriOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF InsertCriOiseau(TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF pOiseau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/UpdateCriOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/UpdateCriOiseauResponse")]
        TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF UpdateCriOiseau(TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF pCriOiseau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeleteCriOiseau", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeleteCriOiseauResponse")]
        string DeleteCriOiseau(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetPhoto", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetPhotoResponse")]
        TEST_Cilent.WCF_Synthese_Remote.PhotoWCF GetPhoto(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/InsertPhoto", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/InsertPhotoResponse")]
        TEST_Cilent.WCF_Synthese_Remote.PhotoWCF InsertPhoto(TEST_Cilent.WCF_Synthese_Remote.PhotoWCF pOiseau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/UpdatePhoto", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/UpdatePhotoResponse")]
        TEST_Cilent.WCF_Synthese_Remote.PhotoWCF UpdatePhoto(TEST_Cilent.WCF_Synthese_Remote.PhotoWCF pPhoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeletePhoto", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeletePhotoResponse")]
        string DeletePhoto(string pID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/ObtenirAlerte", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/ObtenirAlerteResponse")]
        TEST_Cilent.WCF_Synthese_Remote.AlerteWCF[] ObtenirAlerte(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/SupprimerAlertes", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/SupprimerAlertesResponse")]
        bool SupprimerAlertes(TEST_Cilent.WCF_Synthese_Remote.AlerteWCF pAlerte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/AjouterAlertes", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/AjouterAlertesResponse")]
        TEST_Cilent.WCF_Synthese_Remote.AlerteWCF AjouterAlertes(TEST_Cilent.WCF_Synthese_Remote.AlerteWCF pAlerte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/Login", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/LoginResponse")]
        TEST_Cilent.WCF_Synthese_Remote.UsagerWCF Login(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/Logout", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/LogoutResponse")]
        void Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/AddObservation", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/AddObservationResponse")]
        TEST_Cilent.WCF_Synthese_Remote.ObservationDTO AddObservation(TEST_Cilent.WCF_Synthese_Remote.ObservationDTO observation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetObservation", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetObservationResponse")]
        TEST_Cilent.WCF_Synthese_Remote.ObservationDTO GetObservation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetAllObservation", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetAllObservationResponse")]
        TEST_Cilent.WCF_Synthese_Remote.ObservationDTO[] GetAllObservation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/DeleteObservation", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/DeleteObservationResponse")]
        void DeleteObservation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/GetImage", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/GetImageResponse")]
        System.IO.Stream GetImage(string type, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF_Synthese/AddImage", ReplyAction="http://tempuri.org/IServiceWCF_Synthese/AddImageResponse")]
        void AddImage(TEST_Cilent.WCF_Synthese_Remote.ListePhotoObservationDTO listePhoto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCF_SyntheseChannel : TEST_Cilent.WCF_Synthese_Remote.IServiceWCF_Synthese, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCF_SyntheseClient : System.ServiceModel.ClientBase<TEST_Cilent.WCF_Synthese_Remote.IServiceWCF_Synthese>, TEST_Cilent.WCF_Synthese_Remote.IServiceWCF_Synthese {
        
        public ServiceWCF_SyntheseClient() {
        }
        
        public ServiceWCF_SyntheseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCF_SyntheseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCF_SyntheseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCF_SyntheseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteCommentaire(string id) {
            base.Channel.DeleteCommentaire(id);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO AddCommentaire(TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO commentaire) {
            return base.Channel.AddCommentaire(commentaire);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.CommentaireDTO[] GetCommentaire(string id) {
            return base.Channel.GetCommentaire(id);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.UsagerWCF GetUsager(string pID) {
            return base.Channel.GetUsager(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.UsagerWCF InsertUsager(TEST_Cilent.WCF_Synthese_Remote.UsagerWCF pUsager) {
            return base.Channel.InsertUsager(pUsager);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.UsagerWCF UpdateUsager(TEST_Cilent.WCF_Synthese_Remote.UsagerWCF pUsager) {
            return base.Channel.UpdateUsager(pUsager);
        }
        
        public string DeleteUsager(string pID) {
            return base.Channel.DeleteUsager(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCF GetOiseau(string pID) {
            return base.Channel.GetOiseau(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCFList GetAllOiseaux(string pStart, string pQty) {
            return base.Channel.GetAllOiseaux(pStart, pQty);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCF InsertOiseau(TEST_Cilent.WCF_Synthese_Remote.OiseauWCF pOiseau) {
            return base.Channel.InsertOiseau(pOiseau);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.OiseauWCF UpdateOiseau(TEST_Cilent.WCF_Synthese_Remote.OiseauWCF pOiseau) {
            return base.Channel.UpdateOiseau(pOiseau);
        }
        
        public string DeleteOiseau(string pID) {
            return base.Channel.DeleteOiseau(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF GetCriOiseau(string pID) {
            return base.Channel.GetCriOiseau(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF InsertCriOiseau(TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF pOiseau) {
            return base.Channel.InsertCriOiseau(pOiseau);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF UpdateCriOiseau(TEST_Cilent.WCF_Synthese_Remote.CriOiseauWCF pCriOiseau) {
            return base.Channel.UpdateCriOiseau(pCriOiseau);
        }
        
        public string DeleteCriOiseau(string pID) {
            return base.Channel.DeleteCriOiseau(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.PhotoWCF GetPhoto(string pID) {
            return base.Channel.GetPhoto(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.PhotoWCF InsertPhoto(TEST_Cilent.WCF_Synthese_Remote.PhotoWCF pOiseau) {
            return base.Channel.InsertPhoto(pOiseau);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.PhotoWCF UpdatePhoto(TEST_Cilent.WCF_Synthese_Remote.PhotoWCF pPhoto) {
            return base.Channel.UpdatePhoto(pPhoto);
        }
        
        public string DeletePhoto(string pID) {
            return base.Channel.DeletePhoto(pID);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.AlerteWCF[] ObtenirAlerte(string ID) {
            return base.Channel.ObtenirAlerte(ID);
        }
        
        public bool SupprimerAlertes(TEST_Cilent.WCF_Synthese_Remote.AlerteWCF pAlerte) {
            return base.Channel.SupprimerAlertes(pAlerte);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.AlerteWCF AjouterAlertes(TEST_Cilent.WCF_Synthese_Remote.AlerteWCF pAlerte) {
            return base.Channel.AjouterAlertes(pAlerte);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.UsagerWCF Login(string user, string password) {
            return base.Channel.Login(user, password);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.ObservationDTO AddObservation(TEST_Cilent.WCF_Synthese_Remote.ObservationDTO observation) {
            return base.Channel.AddObservation(observation);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.ObservationDTO GetObservation(string id) {
            return base.Channel.GetObservation(id);
        }
        
        public TEST_Cilent.WCF_Synthese_Remote.ObservationDTO[] GetAllObservation() {
            return base.Channel.GetAllObservation();
        }
        
        public void DeleteObservation(string id) {
            base.Channel.DeleteObservation(id);
        }
        
        public System.IO.Stream GetImage(string type, string id) {
            return base.Channel.GetImage(type, id);
        }
        
        public void AddImage(TEST_Cilent.WCF_Synthese_Remote.ListePhotoObservationDTO listePhoto) {
            base.Channel.AddImage(listePhoto);
        }
    }
}
