//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_synthese
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertesusager
    {
        public alertesusager()
        {
            this.alertes = new HashSet<alerte>();
            this.usagers = new HashSet<usager>();
        }
    
        public int IDUsager { get; set; }
        public int IDAlerte { get; set; }
    
        public virtual ICollection<alerte> alertes { get; set; }
        public virtual ICollection<usager> usagers { get; set; }
    }
}
