//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_synthese
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int Id { get; set; }
        public string Texte { get; set; }
        public System.DateTime DateHeure { get; set; }
        public int IDUsager { get; set; }
        public Nullable<int> IDObservation { get; set; }
    
        public virtual usager usagers { get; set; }
        public virtual Observation observation { get; set; }
    }
}
