//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("synthese_dbModel", "FK_OiseauCriOiseau", "oiseau1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Oiseau), "crioiseau1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.CriOiseau), true)]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "FK_OiseauObservation", "oiseau1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Oiseau), "observation1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.Observation), true)]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "FK_OiseauPhoto", "oiseau1", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Oiseau), "photo1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.Photo), true)]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "Alerteobservation", "Alerte", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_synthese.Alerte), "observation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Observation))]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "observationusager", "observation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Observation), "usager", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.Usager), true)]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "PhotoObservationObservation", "PhotoObservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.PhotoObservation), "Observation", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_synthese.Observation))]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "SonObservationObservation", "SonObservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.SonObservation), "Observation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_synthese.Observation))]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "MessageUsagerUsager", "MessageUsager", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.Message), "Usager", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_synthese.Usager))]
[assembly: EdmRelationshipAttribute("synthese_dbModel", "ObservationMessage", "Observation", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Data_synthese.Observation), "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_synthese.Message), true)]

#endregion

namespace Data_synthese
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class synthese_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new synthese_dbEntities object using the connection string found in the 'synthese_dbEntities' section of the application configuration file.
        /// </summary>
        public synthese_dbEntities() : base("name=synthese_dbEntities", "synthese_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new synthese_dbEntities object.
        /// </summary>
        public synthese_dbEntities(string connectionString) : base(connectionString, "synthese_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new synthese_dbEntities object.
        /// </summary>
        public synthese_dbEntities(EntityConnection connection) : base(connection, "synthese_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CriOiseau> CriOiseau
        {
            get
            {
                if ((_CriOiseau == null))
                {
                    _CriOiseau = base.CreateObjectSet<CriOiseau>("CriOiseau");
                }
                return _CriOiseau;
            }
        }
        private ObjectSet<CriOiseau> _CriOiseau;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Observation> Observation
        {
            get
            {
                if ((_Observation == null))
                {
                    _Observation = base.CreateObjectSet<Observation>("Observation");
                }
                return _Observation;
            }
        }
        private ObjectSet<Observation> _Observation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Oiseau> Oiseau
        {
            get
            {
                if ((_Oiseau == null))
                {
                    _Oiseau = base.CreateObjectSet<Oiseau>("Oiseau");
                }
                return _Oiseau;
            }
        }
        private ObjectSet<Oiseau> _Oiseau;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Photo> Photo
        {
            get
            {
                if ((_Photo == null))
                {
                    _Photo = base.CreateObjectSet<Photo>("Photo");
                }
                return _Photo;
            }
        }
        private ObjectSet<Photo> _Photo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usager> Usager
        {
            get
            {
                if ((_Usager == null))
                {
                    _Usager = base.CreateObjectSet<Usager>("Usager");
                }
                return _Usager;
            }
        }
        private ObjectSet<Usager> _Usager;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Message
        {
            get
            {
                if ((_Message == null))
                {
                    _Message = base.CreateObjectSet<Message>("Message");
                }
                return _Message;
            }
        }
        private ObjectSet<Message> _Message;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Alerte> Alerte
        {
            get
            {
                if ((_Alerte == null))
                {
                    _Alerte = base.CreateObjectSet<Alerte>("Alerte");
                }
                return _Alerte;
            }
        }
        private ObjectSet<Alerte> _Alerte;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhotoObservation> PhotoObservationSet
        {
            get
            {
                if ((_PhotoObservationSet == null))
                {
                    _PhotoObservationSet = base.CreateObjectSet<PhotoObservation>("PhotoObservationSet");
                }
                return _PhotoObservationSet;
            }
        }
        private ObjectSet<PhotoObservation> _PhotoObservationSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SonObservation> SonObservationSet
        {
            get
            {
                if ((_SonObservationSet == null))
                {
                    _SonObservationSet = base.CreateObjectSet<SonObservation>("SonObservationSet");
                }
                return _SonObservationSet;
            }
        }
        private ObjectSet<SonObservation> _SonObservationSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CriOiseau EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCriOiseau(CriOiseau criOiseau)
        {
            base.AddObject("CriOiseau", criOiseau);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Observation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObservation(Observation observation)
        {
            base.AddObject("Observation", observation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Oiseau EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOiseau(Oiseau oiseau)
        {
            base.AddObject("Oiseau", oiseau);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Photo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoto(Photo photo)
        {
            base.AddObject("Photo", photo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usager EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsager(Usager usager)
        {
            base.AddObject("Usager", usager);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage(Message message)
        {
            base.AddObject("Message", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Alerte EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlerte(Alerte alerte)
        {
            base.AddObject("Alerte", alerte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhotoObservationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhotoObservationSet(PhotoObservation photoObservation)
        {
            base.AddObject("PhotoObservationSet", photoObservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SonObservationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSonObservationSet(SonObservation sonObservation)
        {
            base.AddObject("SonObservationSet", sonObservation);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Alerte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alerte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Alerte object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="iDObservation">Initial value of the IDObservation property.</param>
        public static Alerte CreateAlerte(global::System.Int32 id, global::System.Int32 iDObservation)
        {
            Alerte alerte = new Alerte();
            alerte.Id = id;
            alerte.IDObservation = iDObservation;
            return alerte;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDObservation
        {
            get
            {
                return _IDObservation;
            }
            set
            {
                OnIDObservationChanging(value);
                ReportPropertyChanging("IDObservation");
                _IDObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObservation");
                OnIDObservationChanged();
            }
        }
        private global::System.Int32 _IDObservation;
        partial void OnIDObservationChanging(global::System.Int32 value);
        partial void OnIDObservationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "Alerteobservation", "observation")]
        public Observation observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.Alerteobservation", "observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.Alerteobservation", "observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> observationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.Alerteobservation", "observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("synthese_dbModel.Alerteobservation", "observation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="CriOiseau")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CriOiseau : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CriOiseau object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="son">Initial value of the Son property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iDOiseau">Initial value of the IDOiseau property.</param>
        public static CriOiseau CreateCriOiseau(global::System.Int32 id, global::System.Byte[] son, global::System.String description, global::System.Int32 iDOiseau)
        {
            CriOiseau criOiseau = new CriOiseau();
            criOiseau.Id = id;
            criOiseau.Son = son;
            criOiseau.Description = description;
            criOiseau.IDOiseau = iDOiseau;
            return criOiseau;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Son
        {
            get
            {
                return StructuralObject.GetValidValue(_Son);
            }
            set
            {
                OnSonChanging(value);
                ReportPropertyChanging("Son");
                _Son = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Son");
                OnSonChanged();
            }
        }
        private global::System.Byte[] _Son;
        partial void OnSonChanging(global::System.Byte[] value);
        partial void OnSonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDOiseau
        {
            get
            {
                return _IDOiseau;
            }
            set
            {
                OnIDOiseauChanging(value);
                ReportPropertyChanging("IDOiseau");
                _IDOiseau = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDOiseau");
                OnIDOiseauChanged();
            }
        }
        private global::System.Int32 _IDOiseau;
        partial void OnIDOiseauChanging(global::System.Int32 value);
        partial void OnIDOiseauChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauCriOiseau", "oiseau1")]
        public Oiseau oiseau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauCriOiseau", "oiseau1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauCriOiseau", "oiseau1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Oiseau> oiseauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauCriOiseau", "oiseau1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauCriOiseau", "oiseau1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="texte">Initial value of the Texte property.</param>
        /// <param name="dateHeure">Initial value of the DateHeure property.</param>
        /// <param name="iDUsager">Initial value of the IDUsager property.</param>
        public static Message CreateMessage(global::System.Int32 id, global::System.String texte, global::System.DateTime dateHeure, global::System.Int32 iDUsager)
        {
            Message message = new Message();
            message.Id = id;
            message.Texte = texte;
            message.DateHeure = dateHeure;
            message.IDUsager = iDUsager;
            return message;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texte
        {
            get
            {
                return _Texte;
            }
            set
            {
                OnTexteChanging(value);
                ReportPropertyChanging("Texte");
                _Texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texte");
                OnTexteChanged();
            }
        }
        private global::System.String _Texte;
        partial void OnTexteChanging(global::System.String value);
        partial void OnTexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateHeure
        {
            get
            {
                return _DateHeure;
            }
            set
            {
                OnDateHeureChanging(value);
                ReportPropertyChanging("DateHeure");
                _DateHeure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateHeure");
                OnDateHeureChanged();
            }
        }
        private global::System.DateTime _DateHeure;
        partial void OnDateHeureChanging(global::System.DateTime value);
        partial void OnDateHeureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsager
        {
            get
            {
                return _IDUsager;
            }
            set
            {
                OnIDUsagerChanging(value);
                ReportPropertyChanging("IDUsager");
                _IDUsager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsager");
                OnIDUsagerChanged();
            }
        }
        private global::System.Int32 _IDUsager;
        partial void OnIDUsagerChanging(global::System.Int32 value);
        partial void OnIDUsagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDObservation
        {
            get
            {
                return _IDObservation;
            }
            set
            {
                OnIDObservationChanging(value);
                ReportPropertyChanging("IDObservation");
                _IDObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObservation");
                OnIDObservationChanged();
            }
        }
        private Nullable<global::System.Int32> _IDObservation;
        partial void OnIDObservationChanging(Nullable<global::System.Int32> value);
        partial void OnIDObservationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "MessageUsagerUsager", "Usager")]
        public Usager Usager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usager>("synthese_dbModel.MessageUsagerUsager", "Usager").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usager>("synthese_dbModel.MessageUsagerUsager", "Usager").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usager> UsagerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usager>("synthese_dbModel.MessageUsagerUsager", "Usager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usager>("synthese_dbModel.MessageUsagerUsager", "Usager", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "ObservationMessage", "Observation")]
        public Observation Observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.ObservationMessage", "Observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.ObservationMessage", "Observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> ObservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.ObservationMessage", "Observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("synthese_dbModel.ObservationMessage", "Observation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Observation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Observation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Observation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateObservation">Initial value of the DateObservation property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="iDUsager">Initial value of the IDUsager property.</param>
        /// <param name="iDOiseau">Initial value of the IDOiseau property.</param>
        public static Observation CreateObservation(global::System.Int32 id, global::System.DateTime dateObservation, global::System.Int32 position, global::System.Int32 iDUsager, global::System.Int32 iDOiseau)
        {
            Observation observation = new Observation();
            observation.Id = id;
            observation.DateObservation = dateObservation;
            observation.Position = position;
            observation.IDUsager = iDUsager;
            observation.IDOiseau = iDOiseau;
            return observation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateObservation
        {
            get
            {
                return _DateObservation;
            }
            set
            {
                OnDateObservationChanging(value);
                ReportPropertyChanging("DateObservation");
                _DateObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateObservation");
                OnDateObservationChanged();
            }
        }
        private global::System.DateTime _DateObservation;
        partial void OnDateObservationChanging(global::System.DateTime value);
        partial void OnDateObservationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.Int32 _Position;
        partial void OnPositionChanging(global::System.Int32 value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsager
        {
            get
            {
                return _IDUsager;
            }
            set
            {
                OnIDUsagerChanging(value);
                ReportPropertyChanging("IDUsager");
                _IDUsager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsager");
                OnIDUsagerChanged();
            }
        }
        private global::System.Int32 _IDUsager;
        partial void OnIDUsagerChanging(global::System.Int32 value);
        partial void OnIDUsagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDOiseau
        {
            get
            {
                return _IDOiseau;
            }
            set
            {
                OnIDOiseauChanging(value);
                ReportPropertyChanging("IDOiseau");
                _IDOiseau = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDOiseau");
                OnIDOiseauChanged();
            }
        }
        private global::System.Int32 _IDOiseau;
        partial void OnIDOiseauChanging(global::System.Int32 value);
        partial void OnIDOiseauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDAlerte
        {
            get
            {
                return _IDAlerte;
            }
            set
            {
                OnIDAlerteChanging(value);
                ReportPropertyChanging("IDAlerte");
                _IDAlerte = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAlerte");
                OnIDAlerteChanged();
            }
        }
        private Nullable<global::System.Int32> _IDAlerte;
        partial void OnIDAlerteChanging(Nullable<global::System.Int32> value);
        partial void OnIDAlerteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauObservation", "oiseau1")]
        public Oiseau oiseau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauObservation", "oiseau1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauObservation", "oiseau1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Oiseau> oiseauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauObservation", "oiseau1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauObservation", "oiseau1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "Alerteobservation", "Alerte")]
        public Alerte Alerte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alerte>("synthese_dbModel.Alerteobservation", "Alerte").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alerte>("synthese_dbModel.Alerteobservation", "Alerte").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Alerte> AlerteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alerte>("synthese_dbModel.Alerteobservation", "Alerte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Alerte>("synthese_dbModel.Alerteobservation", "Alerte", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "observationusager", "usager")]
        public EntityCollection<Usager> usager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usager>("synthese_dbModel.observationusager", "usager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usager>("synthese_dbModel.observationusager", "usager", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "PhotoObservationObservation", "PhotoObservation")]
        public EntityCollection<PhotoObservation> PhotoObservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PhotoObservation>("synthese_dbModel.PhotoObservationObservation", "PhotoObservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PhotoObservation>("synthese_dbModel.PhotoObservationObservation", "PhotoObservation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "SonObservationObservation", "SonObservation")]
        public EntityCollection<SonObservation> SonObservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SonObservation>("synthese_dbModel.SonObservationObservation", "SonObservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SonObservation>("synthese_dbModel.SonObservationObservation", "SonObservation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "ObservationMessage", "Message")]
        public EntityCollection<Message> Message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message>("synthese_dbModel.ObservationMessage", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message>("synthese_dbModel.ObservationMessage", "Message", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Oiseau")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Oiseau : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Oiseau object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="espece">Initial value of the Espece property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iDPhoto">Initial value of the IDPhoto property.</param>
        public static Oiseau CreateOiseau(global::System.Int32 id, global::System.String espece, global::System.String description, global::System.Int32 iDPhoto)
        {
            Oiseau oiseau = new Oiseau();
            oiseau.Id = id;
            oiseau.Espece = espece;
            oiseau.Description = description;
            oiseau.IDPhoto = iDPhoto;
            return oiseau;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Espece
        {
            get
            {
                return _Espece;
            }
            set
            {
                OnEspeceChanging(value);
                ReportPropertyChanging("Espece");
                _Espece = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Espece");
                OnEspeceChanged();
            }
        }
        private global::System.String _Espece;
        partial void OnEspeceChanging(global::System.String value);
        partial void OnEspeceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPhoto
        {
            get
            {
                return _IDPhoto;
            }
            set
            {
                OnIDPhotoChanging(value);
                ReportPropertyChanging("IDPhoto");
                _IDPhoto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPhoto");
                OnIDPhotoChanged();
            }
        }
        private global::System.Int32 _IDPhoto;
        partial void OnIDPhotoChanging(global::System.Int32 value);
        partial void OnIDPhotoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauCriOiseau", "crioiseau1")]
        public EntityCollection<CriOiseau> crioiseaux
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CriOiseau>("synthese_dbModel.FK_OiseauCriOiseau", "crioiseau1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CriOiseau>("synthese_dbModel.FK_OiseauCriOiseau", "crioiseau1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauObservation", "observation1")]
        public EntityCollection<Observation> observations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Observation>("synthese_dbModel.FK_OiseauObservation", "observation1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Observation>("synthese_dbModel.FK_OiseauObservation", "observation1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauPhoto", "photo1")]
        public EntityCollection<Photo> photos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Photo>("synthese_dbModel.FK_OiseauPhoto", "photo1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Photo>("synthese_dbModel.FK_OiseauPhoto", "photo1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Photo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Photo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iDOiseau">Initial value of the IDOiseau property.</param>
        /// <param name="imageMiniature">Initial value of the ImageMiniature property.</param>
        public static Photo CreatePhoto(global::System.Int32 id, global::System.Byte[] image, global::System.String description, global::System.Int32 iDOiseau, global::System.Byte[] imageMiniature)
        {
            Photo photo = new Photo();
            photo.Id = id;
            photo.Image = image;
            photo.Description = description;
            photo.IDOiseau = iDOiseau;
            photo.ImageMiniature = imageMiniature;
            return photo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDOiseau
        {
            get
            {
                return _IDOiseau;
            }
            set
            {
                OnIDOiseauChanging(value);
                ReportPropertyChanging("IDOiseau");
                _IDOiseau = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDOiseau");
                OnIDOiseauChanged();
            }
        }
        private global::System.Int32 _IDOiseau;
        partial void OnIDOiseauChanging(global::System.Int32 value);
        partial void OnIDOiseauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] ImageMiniature
        {
            get
            {
                return StructuralObject.GetValidValue(_ImageMiniature);
            }
            set
            {
                OnImageMiniatureChanging(value);
                ReportPropertyChanging("ImageMiniature");
                _ImageMiniature = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageMiniature");
                OnImageMiniatureChanged();
            }
        }
        private global::System.Byte[] _ImageMiniature;
        partial void OnImageMiniatureChanging(global::System.Byte[] value);
        partial void OnImageMiniatureChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "FK_OiseauPhoto", "oiseau1")]
        public Oiseau oiseau
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauPhoto", "oiseau1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauPhoto", "oiseau1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Oiseau> oiseauReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauPhoto", "oiseau1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Oiseau>("synthese_dbModel.FK_OiseauPhoto", "oiseau1", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="PhotoObservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhotoObservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhotoObservation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iDObservation">Initial value of the IDObservation property.</param>
        /// <param name="imageMiniature">Initial value of the ImageMiniature property.</param>
        /// <param name="commentaire">Initial value of the Commentaire property.</param>
        public static PhotoObservation CreatePhotoObservation(global::System.Int32 id, global::System.Byte[] image, global::System.String description, global::System.Int32 iDObservation, global::System.Byte[] imageMiniature, global::System.String commentaire)
        {
            PhotoObservation photoObservation = new PhotoObservation();
            photoObservation.Id = id;
            photoObservation.Image = image;
            photoObservation.Description = description;
            photoObservation.IDObservation = iDObservation;
            photoObservation.ImageMiniature = imageMiniature;
            photoObservation.Commentaire = commentaire;
            return photoObservation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDObservation
        {
            get
            {
                return _IDObservation;
            }
            set
            {
                OnIDObservationChanging(value);
                ReportPropertyChanging("IDObservation");
                _IDObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObservation");
                OnIDObservationChanged();
            }
        }
        private global::System.Int32 _IDObservation;
        partial void OnIDObservationChanging(global::System.Int32 value);
        partial void OnIDObservationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] ImageMiniature
        {
            get
            {
                return StructuralObject.GetValidValue(_ImageMiniature);
            }
            set
            {
                OnImageMiniatureChanging(value);
                ReportPropertyChanging("ImageMiniature");
                _ImageMiniature = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageMiniature");
                OnImageMiniatureChanged();
            }
        }
        private global::System.Byte[] _ImageMiniature;
        partial void OnImageMiniatureChanging(global::System.Byte[] value);
        partial void OnImageMiniatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Commentaire
        {
            get
            {
                return _Commentaire;
            }
            set
            {
                OnCommentaireChanging(value);
                ReportPropertyChanging("Commentaire");
                _Commentaire = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Commentaire");
                OnCommentaireChanged();
            }
        }
        private global::System.String _Commentaire;
        partial void OnCommentaireChanging(global::System.String value);
        partial void OnCommentaireChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "PhotoObservationObservation", "Observation")]
        public Observation Observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.PhotoObservationObservation", "Observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.PhotoObservationObservation", "Observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> ObservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.PhotoObservationObservation", "Observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("synthese_dbModel.PhotoObservationObservation", "Observation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="SonObservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SonObservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SonObservation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="son">Initial value of the Son property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="iDObservation">Initial value of the IDObservation property.</param>
        public static SonObservation CreateSonObservation(global::System.Int32 id, global::System.Byte[] son, global::System.String description, global::System.Int32 iDObservation)
        {
            SonObservation sonObservation = new SonObservation();
            sonObservation.Id = id;
            sonObservation.Son = son;
            sonObservation.Description = description;
            sonObservation.IDObservation = iDObservation;
            return sonObservation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Son
        {
            get
            {
                return StructuralObject.GetValidValue(_Son);
            }
            set
            {
                OnSonChanging(value);
                ReportPropertyChanging("Son");
                _Son = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Son");
                OnSonChanged();
            }
        }
        private global::System.Byte[] _Son;
        partial void OnSonChanging(global::System.Byte[] value);
        partial void OnSonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDObservation
        {
            get
            {
                return _IDObservation;
            }
            set
            {
                OnIDObservationChanging(value);
                ReportPropertyChanging("IDObservation");
                _IDObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObservation");
                OnIDObservationChanged();
            }
        }
        private global::System.Int32 _IDObservation;
        partial void OnIDObservationChanging(global::System.Int32 value);
        partial void OnIDObservationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "SonObservationObservation", "Observation")]
        public Observation Observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.SonObservationObservation", "Observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.SonObservationObservation", "Observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> ObservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.SonObservationObservation", "Observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("synthese_dbModel.SonObservationObservation", "Observation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="synthese_dbModel", Name="Usager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usager object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nomUsager">Initial value of the NomUsager property.</param>
        /// <param name="motPasse">Initial value of the MotPasse property.</param>
        /// <param name="administrateur">Initial value of the Administrateur property.</param>
        /// <param name="iDObservation">Initial value of the IDObservation property.</param>
        public static Usager CreateUsager(global::System.Int32 id, global::System.String nomUsager, global::System.String motPasse, global::System.Boolean administrateur, global::System.Int32 iDObservation)
        {
            Usager usager = new Usager();
            usager.Id = id;
            usager.NomUsager = nomUsager;
            usager.MotPasse = motPasse;
            usager.Administrateur = administrateur;
            usager.IDObservation = iDObservation;
            return usager;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomUsager
        {
            get
            {
                return _NomUsager;
            }
            set
            {
                OnNomUsagerChanging(value);
                ReportPropertyChanging("NomUsager");
                _NomUsager = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomUsager");
                OnNomUsagerChanged();
            }
        }
        private global::System.String _NomUsager;
        partial void OnNomUsagerChanging(global::System.String value);
        partial void OnNomUsagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MotPasse
        {
            get
            {
                return _MotPasse;
            }
            set
            {
                OnMotPasseChanging(value);
                ReportPropertyChanging("MotPasse");
                _MotPasse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MotPasse");
                OnMotPasseChanged();
            }
        }
        private global::System.String _MotPasse;
        partial void OnMotPasseChanging(global::System.String value);
        partial void OnMotPasseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Administrateur
        {
            get
            {
                return _Administrateur;
            }
            set
            {
                OnAdministrateurChanging(value);
                ReportPropertyChanging("Administrateur");
                _Administrateur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Administrateur");
                OnAdministrateurChanged();
            }
        }
        private global::System.Boolean _Administrateur;
        partial void OnAdministrateurChanging(global::System.Boolean value);
        partial void OnAdministrateurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDObservation
        {
            get
            {
                return _IDObservation;
            }
            set
            {
                OnIDObservationChanging(value);
                ReportPropertyChanging("IDObservation");
                _IDObservation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDObservation");
                OnIDObservationChanged();
            }
        }
        private global::System.Int32 _IDObservation;
        partial void OnIDObservationChanging(global::System.Int32 value);
        partial void OnIDObservationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "observationusager", "observation")]
        public Observation observation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.observationusager", "observation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.observationusager", "observation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Observation> observationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Observation>("synthese_dbModel.observationusager", "observation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Observation>("synthese_dbModel.observationusager", "observation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("synthese_dbModel", "MessageUsagerUsager", "MessageUsager")]
        public EntityCollection<Message> MessageUsager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message>("synthese_dbModel.MessageUsagerUsager", "MessageUsager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message>("synthese_dbModel.MessageUsagerUsager", "MessageUsager", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
