//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_synthese
{
    using System;
    using System.Collections.Generic;
    
    public partial class observation
    {
        public int Id { get; set; }
        public System.DateTime DateObservation { get; set; }
        public int Position { get; set; }
        public int IDUsager { get; set; }
        public int IDOiseau { get; set; }
        public int UsagerId { get; set; }
        public int SonObservationId { get; set; }
        public int PhotoObservationId { get; set; }
    
        public virtual oiseau oiseaux { get; set; }
        public virtual photoobservation photoobservations { get; set; }
        public virtual sonobservation sonobservations { get; set; }
        public virtual usager usagers { get; set; }
    }
}
