//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_synthese
{
    using System;
    using System.Collections.Generic;
    
    public partial class observation
    {
        public observation()
        {
            this.photoobservations = new HashSet<photoobservation>();
            this.sonobservations = new HashSet<sonobservation>();
            this.message = new HashSet<message>();
            this.Commentaire = new HashSet<Commentaire>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateObservation { get; set; }
        public Nullable<int> PositionLong { get; set; }
        public int IDUsager { get; set; }
        public int IDOiseau { get; set; }
        public string PositionLat { get; set; }
    
        public virtual oiseau oiseaux { get; set; }
        public virtual ICollection<photoobservation> photoobservations { get; set; }
        public virtual ICollection<sonobservation> sonobservations { get; set; }
        public virtual usager usagers { get; set; }
        public virtual ICollection<message> message { get; set; }
        public virtual ICollection<Commentaire> Commentaire { get; set; }
    }
}
