//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_synthese
{
    using System;
    using System.Collections.Generic;
    
    public partial class usager
    {
        public usager()
        {
            this.messages = new HashSet<message>();
            this.observations = new HashSet<observation>();
            this.alerte = new HashSet<alerte>();
            this.Commentaire = new HashSet<Commentaire>();
        }
    
        public int Id { get; set; }
        public string NomUsager { get; set; }
        public string MotPasse { get; set; }
        public bool Administrateur { get; set; }
        public string Courriel { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<message> messages { get; set; }
        public virtual ICollection<observation> observations { get; set; }
        public virtual ICollection<alerte> alerte { get; set; }
        public virtual ICollection<Commentaire> Commentaire { get; set; }
    }
}
